version: '3.11'

services:
  prod:
    build:
      context: .
    ports:
      - "8001:8001"
    networks:
      mynetwork:
        ipv4_address: 172.25.0.2
    volumes:
      - static_data:/vol/web
    environment:
      - SECRET_KEY=samplesecret123
      - ALLOWED_HOSTS=127.0.0.1,localhost

  proxy:
    build:
      context: ./proxy
    network_mode: host
    volumes:
      - static_data:/vol/static
    ports:
      - "8080:8080"
    depends_on:
      - prod
volumes:
  static_data:

networks:
  mynetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16