version: "3.11"

services:
  test:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./base:/base
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=1
